### ISSUE TITLE
Preferences pop over does not scroll when opened at edge of the screen

### ISSUE THREAD

**Issue by lightonflux** [jorchube/monitorets#15]
![Bildschirmfoto vom 2022-12-11 22-27-00](https://user-images.githubusercontent.com/1377943/206930042-3b7df6ae-f320-41c5-a595-45917bfaba4a.png)

When the window is near the edge of the screen the pop over will open, but the content is to much to display. Sadly the pop over menu does not scroll.

**Comment by jrdmellow** [comment]
I have this issue as well. On my PC it lists 8 separate cores as well as several NVME sensors. With the large font used it easily runs off the screen, making most of the list unselectable.

**Comment by jorchube** [comment]
Thank you for reporting this issue. I'll look into it as soon as possible.

**Comment by jorchube** [comment]
FYI: Version 0.6.90 with a reworked preferences that should fix this issue interface should hit flathub beta channel in the following hours.

**Comment by jorchube** [comment]
Closing this as it is addressed in  version 0.7.0.
