### ISSUE TITLE
Use shorter default labels or allow custom labels

### ISSUE THREAD

**Issue by lightonflux** [jorchube/monitorets#20]
![Bildschirmfoto vom 2022-12-29 18-02-26](https://user-images.githubusercontent.com/1377943/209985379-fc3e439c-3e97-4bc7-af0a-894f96939cae.png)

Some labels are quite long (and also wrong color). Which becomes a problem if the app window is narrow:

![image](https://user-images.githubusercontent.com/1377943/209985502-c8998a00-4553-4fbf-8c17-85274be337c2.png)

Instead of "Temp ($sensor)" the default text could be something like "🌡️ amdgpu-edge" which would save 6 chars. 

Especially for temp sensors it would be nice to set custom labels in the settings.

**Comment by jorchube** [comment]
Both ideas, using an emoji and being able to set custom labels, are very good suggestions. I will look into them.

**Comment by jorchube** [comment]
Closing this as it is addressed in version 0.7.0
