### ISSUE TITLE
Use same scaling for network up and down

### ISSUE THREAD

**Issue by lightonflux** [jorchube/monitorets#21]
![image](https://user-images.githubusercontent.com/1377943/209986082-be154a5d-aaf9-43cb-86f5-67b1ee29803d.png)

By default, the scaling make it appear as if my connection and network use were symmetrical. I think it would be more intuitive to use the same scaling for both by default. Maybe with an option for independent auto-scaling. Otherwise the app needs to add a scale, so the user can discern that there is a difference in up-/down stream.

**Comment by jorchube** [comment]
Yes, you are right in that it can be confusing as there is no reference of any kind. I'll see what can be done.

**Comment by jorchube** [comment]
Version 0.8.0 has been set up so that uplink and downlink monitors use the same scaling. It will be released in flathub in the coming hours, so I'm closing this issue ;)
