### ISSUE TITLE
Better distinction between hints and about

### ISSUE THREAD

**Issue by gregorni** [jorchube/monitorets#28]
The "Hints and Tips" and "About" button should be more different, it's weird to see 2 identical buttons with different functions in the bottom right corner.
Perhaps the icon for "Hints and Tips" could be changed to a question mark or something of the sort?

**Comment by jorchube** [comment]
Hi!

As with the other issue you have opened, I am inclined to think that you have installed a custom iconset. These are the intended tips and about buttons in the stable branch currently:

![image](https://user-images.githubusercontent.com/1174736/211194967-f4c53274-b43a-48b4-a095-50dc7eb948e9.png)

**Comment by gregorni** [comment]
This is what it looks like with me: 

![Screenshot_2023-01-08_14-24-32](https://user-images.githubusercontent.com/119804311/211198511-974ab6de-4831-4ef4-bb65-897c66f7cb7b.png)

This is on the latest Flatpak, though, I don't know if this has been updated since then. Or it might also just be my distro messing up.

**Comment by jorchube** [comment]
That is definitely not libadwaita theme and iconset.

What distribution are you using?

**Comment by gregorni** [comment]
> That is definitely not libadwaita’s iconset.
> 
> What distribution are you using?

Pop!_OS

**Comment by jorchube** [comment]
Closing this as it no longer applies for version 0.7.0.
