### ISSUE TITLE
Feature request - Values shown

### ISSUE THREAD

**Issue by RuneFFF** [jorchube/monitorets#32]
It would be great if there was a togglable option to show the values of the sensors - maybe in a line below the sensor name insidde the graph.

**Comment by jorchube** [comment]
Hello!

Indeed that is an interesting suggestion! :)

This is a feature that I was evaluating when/how to do, and I still am. So it will land at some point, probably ;)

**Comment by jorchube** [comment]
Ability to show values has been added to version 0.8.0 (soon published in flathub), so I'll be closing this issue now ;)
