### ISSUE TITLE
0.9.0: labels off center

### ISSUE THREAD

**Issue by lightonflux** [jorchube/monitorets#70]
Since the update to 0.9.0 the labels are not centred vertically any more. Is this intended? Looks unintended. 
![grafik](https://user-images.githubusercontent.com/1377943/216841821-7908adc4-e6a6-4b1e-9e47-dfbe2e0e7d56.png)

**Comment by jorchube** [comment]
Yes, this is unintended. Thank you for reporting it.

**Comment by jorchube** [comment]
Version 0.9.2 is out with the intended alignment.
