### ISSUE TITLE
Network traffic icons (arrows?) missing.

### ISSUE THREAD

**Issue by nicocarbone** [jorchube/monitorets#75]
The issue can more easily be seen on the attached image.
The network traffic monitors have a weird icon in place of, I assume, arrows signaling upload/download. 
![Captura desde 2023-02-11 19-15-51](https://user-images.githubusercontent.com/9342423/218283427-3a5f374a-ddd4-4c81-ab90-99f850ea0680.png)

**Comment by jorchube** [comment]
Hello!

Thanks for taking the time to report this.

May I ask which distribution are you using?

It looks like neither icons nor fonts are the ones used by LibAdwaita. In that case there is not much I can do, as it is not a Monitorets problem, but a problem with your font, which does not have the expected up and down arrow glyphs.

As a workaround if you want to keep / cannot change the font, may a suggest that you rename those monitors to something else of your liking?
You can do that by hovering on a monitor and clicking the "pencil" icon:

[Screencast from 2023-02-12 18-36-04.webm](https://user-images.githubusercontent.com/1174736/218327285-4baf92f6-87d4-4a26-a04a-52ba08826c2d.webm)

**Comment by nicocarbone** [comment]
Hello.

Thank you for your reply.

I am using Ubuntu 22.10. I installed the using flatpak.

I will try the suggested workarounds.
