### ISSUE TITLE
I need to monitor my CPU, RAM, motherboard?, GPU & SSD, which of these should I toggle on? 

### ISSUE THREAD

**Issue by Intellectual234** [jorchube/monitorets#77]
And also, does your program keep logs, in case of a overheat shutdown, i can reboot & go look at what the temps were of each component? the problem maker?  -Thanks!

![image](https://user-images.githubusercontent.com/105397593/222864188-3e09a86e-5ca1-42d5-8704-76143176b786.png)

**Comment by jorchube** [comment]
Hello!

The sensors shown by Monitorets are completely dependent on your hardware, and their names are dependent on the driver that has discovered them, the manufacturer, etc. So Monitorets has no control over what each one of those mean.

I can tell that the "coretemp" ones are CPU, "dell_smm-SODIMM" seems to be your RAM, "dell_smm-CPU" should also be CPU and "dell_smm-GPU" should be GPU. Besides that, I don't know.

Regarding an "overheat shutdown" I think it would be a better idea if you look at system logs such as journalctl. It will give you a better overview.

Regards!

**Comment by Intellectual234** [comment]
@jorchube , Thanks Jordi!
