### ISSUE TITLE
Feature request: system tray/top bar support

### ISSUE THREAD

**Issue by talal** [jorchube/monitorets#87]
Hi,

First of all thank you for the great app!

Would it be possible for you to add system tray/top bar support, where we can select some sensors and have their values show in the top bar?

I currently use [psensor](https://wpitchoune.net/psensor/) for this (screenshot down below). psensor allows you to select sensors and then their values are shown in the top bar. If you click on it then it shows all the sensor values right there in the top bar.

I think this feature would be a great addition to Monitorets as this would allow us to keep an eye on specific sensor values by having them show in the top bar.  

![image](https://github.com/jorchube/monitorets/assets/3526562/b9f0b7aa-0edb-481b-9006-a4c5b8134ee1)

**Comment by gregorni** [comment]
The system tray on is not supported on GNOME 44 for apps, only for GNOME Extensions. The best replacement for the moment is the background apps portal, but that won't really achieve the functionality you're aiming for.

**Comment by talal** [comment]
I think system tray for apps is possible if you use the [AppIndicator extension](https://extensions.gnome.org/extension/615/appindicator-support/) but I'm not 100% sure on this.

Maybe @jorchube can provide his feedback on this.

**Comment by gregorni** [comment]
System tray does work with the AppIndicator extension, I had forgotten about that. I had meant vanilla GNOME, but a lot of people do use the AppIndicator extension.

> Maybe @jorchube can provide his feedback on this.

Yes, let's wait for their opinion.

**Comment by jorchube** [comment]
Hello!

Truth be told, this is something that I have no interest to implement.

I am one of those weirdos that use gnome without any extension and I do not like to put stuff on the system tray. Besides, it seems that that niche is already covered ;)

Moreover, Monitorets has already more features that what I initially planned, so I don't want to make it more complex. I would have to (and I will) do some heavy refactors and fixes before thinking about adding any more functionality to it.

**Comment by talal** [comment]
I understand. Thanks for your response :)
